version: '3'

services:
    postgres:
        image: postgres:alpine3.14
        # Start postgres on port 4999
        command: -p 5000
        environment:
            # config the superuser name and pw
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testDb
        ports:
            - "5000:5000"
